'use client'
import { useEffect, useState } from "react";
import "./globals.scss";
import StoreProvider from "./StoreProvider";
// import { useRouter } from "next/router";

// const inter = Inter({ subsets: ["poppins"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const handleLoading = () => {
//   const [isLoading, setIsLoading] = useState(false);
//   const router = useRouter();

//   useEffect(() => {
//     const handleStart = (url) => (url !== router.asPath) && setIsLoading(true)
//     const handleComplete = (url) => (url === router.asPath) && setTimeout(() => {
//       setIsLoading(false)
//     }, 5000);

//     router.events.on("routerChangeStart", handleStart)
//     router.events.on("routerChangeComplete", handleComplete)
//     router.events.on("routerChangeError", handleComplete)

//     return () => {
//       router.events.off("routerChangeStart", handleStart)
//       router.events.off("routerChangeComplete", handleComplete)
//       router.events.off("routerChangeError", handleComplete)
//     }
//   })

//   return (
//     <div className="loading-container">
//       <div className="loading">
//         <div className="loading-icon">
//           <h1>loading...</h1>
//         </div>
//       </div>
//     </div>
//   )
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Relzi Wallet</title>
        <meta name="description" content="Supercharge your brand! Code By Pro offers: Website and App Development, UX/UI Design, Logos, SEO, SMM, Video Animation. Get a free quote & grow!" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"></link>

        <link rel="icon" href="/relzi-svg.svg" />
      </head>
      <body style={{ fontFamily: 'Poppins, sans-serif' }}>
        <StoreProvider>
          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
